In [1]:
from keras.models import Model
from keras.layers import Input, LSTM, GRU
import numpy as np
import matplotlib.pyplot as plt

In [2]:
T = 8   # sequence length 
D = 2   # input Dimensionality
M = 3   # hidden layer size

In [3]:
# create one sample of size T * D
X = np.random.randn(1, T, D)

In [17]:
def lstm1():
  input_ = Input( shape=(T, D)  )
  rnn = LSTM(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  # note that lstm has 2 states (hidden state, cell state)
  o, h, c = model.predict(X)
  o, h, c = model.predict(X)
  print('output from lstm:', o, '  ---  output shape:', o.shape)    # 1 * M
  print('hiddin state:', h, '  ---  hidden state shape:', h.shape)  # 1 * M
  print('cell state:', c, '  ---  cell state shape:', c.shape)      # 1 * M

In [19]:
def lstm2():
  input_ = Input( shape=(T, D)  )
  rnn = LSTM(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  # note that lstm has 2 states (hidden state, cell state)
  o, h, c = model.predict(X)
  print('output from lstm:', o, '  ---  output shape:', o.shape)    # 1 * T * M
  print('hiddin state:', h, '  ---  hidden state shape:', h.shape)  # 1 * M
  print('cell state:', c, '  ---  cell state shape:', c.shape)      # 1 * M

In [20]:
def gru1():
  input_ = Input( shape=(T, D)  )
  rnn = GRU(M, return_state=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  # note that gru has one states (hidden state)
  o, h = model.predict(X)
  print('output from gru:', o, '  ---  output shape:', o.shape)     # 1 * M
  print('hiddin state:', h, '  ---  hidden state shape:', h.shape)  # 1 * M

In [21]:
def gru2():
  input_ = Input( shape=(T, D)  )
  rnn = GRU(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = Model(inputs=input_, outputs=x)
  # note that gru has one states (hidden state)
  o, h = model.predict(X)
  print('output from gru:', o, '  ---  output shape:', o.shape)     # 1 * T * M
  print('hiddin state:', h, '  ---  hidden state shape:', h.shape)  # 1 * M

In [22]:
# note that the output of the lstm is the same as hidden state o = h
print("lstm1: ")
lstm1()

lstm1: 
output from lstm: [[ 0.26827934 -0.04583582 -0.00368152]]   ---  output shape: (1, 3)
hiddin state: [[ 0.26827934 -0.04583582 -0.00368152]]   ---  hidden state shape: (1, 3)
cell state: [[ 0.5424243  -0.08238004 -0.00850592]]   ---  cell state shape: (1, 3)


In [24]:
# note that the last output of the lstm is the same as hidden state o = h
# h can represent final hidden state
print("lstm2: ")
lstm2()

lstm2: 
output from lstm: [[[ 0.16872203 -0.18486582  0.14565213]
  [ 0.2127605  -0.22613025  0.20254228]
  [ 0.09995212 -0.19356297  0.17493823]
  [ 0.07206473 -0.19600245  0.23357859]
  [-0.00242768 -0.16893849  0.23150197]
  [ 0.10649157 -0.30267763  0.11773311]
  [ 0.19319306 -0.35885966  0.06553325]
  [ 0.13764481 -0.23675025  0.11594554]]]   ---  output shape: (1, 8, 3)
hiddin state: [[ 0.13764481 -0.23675025  0.11594554]]   ---  hidden state shape: (1, 3)
cell state: [[ 0.26894858 -0.607115    0.2768499 ]]   ---  cell state shape: (1, 3)


In [25]:
# note that the output of the gru is the same as hidden state o = h
print("gru1: ")
gru1()

gru1: 
output from gru: [[ 0.01974733 -0.15589392 -0.41079798]]   ---  output shape: (1, 3)
hiddin state: [[ 0.01974733 -0.15589392 -0.41079798]]   ---  hidden state shape: (1, 3)


In [26]:
# note that the last output of the gru is the same as hidden state o = h
# h can represent final hidden state
print("gru2: ")
gru2()

gru2: 
output from gru: [[[ 0.0895775   0.21014312 -0.39184043]
  [ 0.05880295  0.344826   -0.54534066]
  [-0.07368715  0.28666133 -0.31331024]
  [-0.04431956  0.31364888 -0.42130035]
  [-0.07757439  0.28808144 -0.37538788]
  [-0.11764138 -0.09011286  0.12564448]
  [-0.07954364 -0.2712819  -0.09384297]
  [ 0.00261473 -0.02355063 -0.22192647]]]   ---  output shape: (1, 8, 3)
hiddin state: [[ 0.00261473 -0.02355063 -0.22192647]]   ---  hidden state shape: (1, 3)
